name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feat"]
  - title: "🐛 Fixes"
    labels: ["fix"]
  - title: "⚙️ Performance"
    labels: ["perf"]
  - title: "🧹 Refactors"
    labels: ["refactor"]
  - title: "🧪 Tests"
    labels: ["test"]
  - title: "📚 Docs"
    labels: ["docs"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## What’s Changed
  $CHANGES
