name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Affected package/module in the monorepo
      options:
        - core
        - assets
        - app_bootstrap
        - repo
    validations:
      required: true

  - type: input
    id: vago
    attributes:
      label: Task ID (optional)
      description: Link to tracker task, e.g. VAGO-123
      placeholder: VAGO-123

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear, concise description of the bug.
      placeholder: The app crashes when ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Be precise. Include data, account, environment.
      placeholder: |
        1. Open ...
        2. Tap ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: It should ...
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        Flutter: x.x.x (channel stable)
        Platform: iOS/Android/Web
        Device/OS: ...
        App version: ...
        Affected paths: packages/<name>/...
    validations:
      required: false

  - type: textarea
    id: attachments
    attributes:
      label: Logs / Screenshots / Video
      placeholder: Paste logs or attach files
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance criteria
      options:
        - label: Repro steps covered by tests where reasonable
        - label: CI green (format, analyze, tests)
        - label: Linked PR references this issue