name: Chore & Infra
description: Maintenance, build/CI changes, refactors, housekeeping
labels: [chore]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - core
        - assets
        - app_bootstrap
        - repo
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - build
        - ci
        - refactor
        - performance
        - test
        - housekeeping
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What/why/how?
    validations:
      required: true

  - type: textarea
    id: paths
    attributes:
      label: Affected paths
      placeholder: |
        packages/core/**
        .github/workflows/**
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance criteria
      options:
        - label: No functional change (if refactor/housekeeping)
        - label: CI green (format/analyze/tests)
        - label: Coverage not degraded (where applicable)
        - label: Docs updated if needed