name: Documentation
description: Improve or add documentation
labels: [documentation]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - core
        - assets
        - app_bootstrap
        - repo
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: What to document?
      placeholder: |
        Update README in packages/core
        Add ADR for ...
    validations:
      required: true

  - type: checkboxes
    id: targets
    attributes:
      label: Targets
      options:
        - label: README
        - label: ADR
        - label: API docs
        - label: Developer guide
        - label: Contribution guide

  - type: textarea
    id: links
    attributes:
      label: Related links
      placeholder: Design doc / PR / issue links