name: Feature Request
description: Propose a new feature or enhancement
labels: [feature]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - core
        - assets
        - app_bootstrap
        - repo
    validations:
      required: true

  - type: input
    id: vago
    attributes:
      label: Task ID (optional)
      placeholder: VAGO-123

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the user/business need?
      placeholder: As a <user>, I want ...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details / Constraints
      placeholder: UX notes, edge cases, non-goals, risks
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (DoD)
      value: |
        - [ ] Scenarios documented
        - [ ] Feature flags (if needed)
        - [ ] CI green (format/analyze/tests)
        - [ ] Docs updated (README/ADR)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact / Metrics (optional)
      placeholder: Performance, adoption, error rate targets, etc.