name: Flutter CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install melos
        run: dart pub global activate melos

      - name: Bootstrap workspace
        run: melos bootstrap

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: melos run analyze

      - name: Test
        run: melos run test

      # Debug builds без емуляторів
      - name: Build app_qubit (debug)
        working-directory: apps/app_qubit
        run: flutter build apk --debug

      - name: Build app_riverpod (debug)
        working-directory: apps/app_riverpod
        run: flutter build apk --debug
