name: core

description: >
  A centralized Flutter package containing the shared codebase for all
  applications in the monorepo. Organized into reusable feature modules
  (Animations, Error Handling, Localization, Navigation, Overlays, Theme, etc.)
  and layered architecture (Data, Domain, Presentation) to ensure consistency,
  maintainability, and rapid development across multiple app variants.

version: 0.1.0+1
publish_to: none
environment:
  sdk: ^3.8.0
  flutter: ">=3.22.0"

dependencies:
  cloud_firestore: ^5.4.0
  collection: ^1.18.0
  dio: ^5.9.0
  easy_localization: ^3.0.5
  equatable: ^2.0.7
  firebase_auth: ^5.3.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  intl: ^0.20.2
  logger: ^2.3.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
