name: core

description: >
  A centralized Flutter package containing the shared codebase for all applications
  in the monorepo. Organized into reusable feature modules (Animations, Error Handling, 
  Localization, Navigation, Overlays, Theme, etc.) and layered architecture 
  (Data, Domain, Presentation) to ensure consistency, maintainability, and 
  rapid development across multiple app variants.

version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
