# Base ruleset from Very Good Ventures (includes recommended Flutter & Dart lints)
include: package:very_good_analysis/analysis_options.yaml
#

# Linter rules overrides
# ----------------------
linter:
  rules:
    # Prefer const literals for immutable collections to improve performance
    prefer_const_literals_to_create_immutables: true
    # Allow omitting curly braces in single-line control flow statements
    curly_braces_in_flow_control_structures: false
    # Allow lines up to 120 characters
    lines_longer_than_80_chars: false
    #

    #
    #

# Custom lint plugin configuration (Riverpod-related rules)
# ---------------------------------------------------------
custom_lint:
  # Disable all custom lint rules by default
  enabled_all_lint_rules: false
  rules:
    # Do not enforce having a ProviderScope at the root widget
    missing_provider_scope: false
    # Do not require generated provider dependency annotations
    generated_provider_dependency: false
    #
    #

# Analyzer configuration
# ----------------------
analyzer:
  # Enable custom_lint plugin for additional lint checks
  plugins:
    - custom_lint

  # Exclude generated files and non-Dart resources from analysis
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/models/*.freezed.dart"
    - "lib/models/*.g.dart"
    - "**/docs/**"
    - "*.md"
    - "**/*.md"
    - "**/firebase_options.dart"

  # Override severity levels for specific rules
  errors:
    # Show warnings instead of errors for invalid annotation targets
    invalid_annotation_target: warning
    # Ignore deprecated member usage warnings
    deprecated_member_use: ignore
