name: assets

description: Shared assets (images, translations, fonts) for apps in the monorepo.

version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/translations/
    - assets/images/

  fonts:
    # Main font: IBM Plex Sans (variable: wght 100–900, wdth; + italic)
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

    # Accent font: Montserrat (variable: wght 100–900; + italic)
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
