name: app_on_riverpod
description: Demo app (on Riverpod)
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  app_bootstrap:
    path: ../../packages/app_bootstrap
  assets:
    path: ../../packages/assets
  bloc: ^9.0.0
  cloud_firestore: ^6.0.0
  core:
    path: ../../packages/core
  device_info_plus: ^11.5.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  go_router: ^16.1.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  # generate: true
  uses-material-design: true
